#!/bin/sh
qr_folder="/Users/${users}/.qrcode"
list=$(ls -1 ${qr_folder})

get_code() {
    zbarimg "${qr_folder}/${1}" 2> /dev/null \
        | grep -Eo "secret=[[:alnum:]]*" \
        | cut -d "=" -f 2 \
        | totp
}

search() {
    echo 123
}

ask_setting() {
    echo "${list}\n"
    read -er -p "Please input qrcode file name: " qr_name
}

if [ ${#} -eq 1 ]; then
    qr_name=${1}
else
    ask_setting
fi

qr_name=$(echo "${list}" | grep ${qr_name})
if [ ${?} -ne 0 ]; then
    echo "File not found!"
elif [ $(echo "${qr_name}" | wc -l) -ne 1 ]; then
    echo "Too many file names macth: \n"
    echo "${qr_name}"
else
    code=$(get_code ${qr_name})
    echo ${qr_name%.*} code: ${code}
    echo ${code} | pbcopy
fi
