global:
  resolve_timeout: 5m
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 30m
  receiver: 'slack.hook'
receivers:
- name: 'slack.hook'
  slack_configs: 
  # Whether or not to notify about resolved alerts.
  - send_resolved: true

    api_url: [<secret>]

    # The channel or user to send notifications to.
    channel: '#alerting'
    username: 'Grafana'
    text: "<!channel> \nsummary: {{ .CommonAnnotations.summary }}\ndescription: {{ .CommonAnnotations.description }}"
