global:
  resolve_timeout: 5m

route:
  receiver: 'web.hook'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'

inhibit_rules:
- target_match:
    severity: 'warning'
- source_match:
    severity: 'critical'
- equal: ['alertname', 'dev', 'instance']